### ISSUE TITLE
Broken font loading from fonts.openalias.org

### ISSUE THREAD

**Issue by nabijaczleweli** [openalias/openalias-website#2]
As of right now, requests to `fonts.openalias.org` fail:

> downloadable font: download failed (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:1): bad URI or cross-site access not allowed source: https://fonts.openalias.org/font/fontawesome-webfont.woff?v=4.2.0

Which makes the first page look less than appealing:

![SS](https://user-images.githubusercontent.com/6709544/30513343-ee0ca8c2-9b01-11e7-9563-29743789506d.png)

Even though that error is printed out, the request seems to complete and return the font, so, while it looks like an XSS issue, it might not be?

**Comment by fluffypony** [comment]
@nabijaczleweli I added CORS headers - try now?

**Comment by nabijaczleweli** [comment]
No change in behaviour.

**Comment by fluffypony** [comment]
@nabijaczleweli which browser, OS, and version?

**Comment by nabijaczleweli** [comment]
Firefox Developer Edition 56.0b11 (64-bit)
Windows 10 Home 1607 64-bit

**Comment by fluffypony** [comment]
@nabijaczleweli try clear your cache and hard-refresh with dev tools open, should see access-control-allowed-origin headers in the response as in the attached image.
![screen shot 2017-09-16 at 8 28 54 pm](https://user-images.githubusercontent.com/1944293/30514858-d43a45a0-9b1d-11e7-8b66-182d1a18b7ba.png)

**Comment by nabijaczleweli** [comment]
Weird, looks like I'm not getting those headers at all:
![SS](https://user-images.githubusercontent.com/6709544/30514910-ed313b62-9b1e-11e7-8dc5-69b017c978fd.png)

**Comment by nabijaczleweli** [comment]
They do, however, exist when dumped with cURL:
```
> curl -SL -DCON https://fonts.openalias.org/font/fontawesome-webfont.woff?v=4.2.0 -o t:\asdf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/2 200
date: Sat, 16 Sep 2017 18:39:21 GMT
content-type: application/octet-stream
content-length: 65452
set-cookie: __cfduid=d99d061545fe53228dd09a861b3ef48a61505587161; expires=Sun, 16-Sep-18 18:39:21 GMT; path=/; domain=.openalias.org; HttpOnly
last-modified: Thu, 16 Feb 2017 20:47:25 GMT
etag: "58a60fdd-ffac"
access-control-allow-credentials: true
access-control-allow-methods: GET, POST, OPTIONS
access-control-allow-headers: DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type
cf-cache-status: HIT
expires: Mon, 02 Oct 2017 18:39:21 GMT
cache-control: public, max-age=1382400
accept-ranges: bytes
server: cloudflare-nginx
cf-ray: 39f5f2aeb96140f4-HAM

100 65452  100 65452    0     0  65452      0  0:00:01 --:--:--  0:00:01  124k
```

**Comment by fluffypony** [comment]
Weird - Firefox cache maybe?

**Comment by nabijaczleweli** [comment]
Weird, indeed. I cleaned out the cache, but that may be possible. And it works in IE, so probably FF interaction.

**Comment by fluffypony** [comment]
Closing as "probably Firefox" :-P
